Traceback (most recent call last):
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DiskFull: could not write to file "base/pgsql_tmp/pgsql_tmp2510281.0": No space left on device


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/curve-lp-metrics/curvemetrics/scripts/forever.py", line 226, in main
    t = datahandler.get_takers()
  File "/root/curve-lp-metrics/curvemetrics/src/classes/datahandler.py", line 606, in get_takers
    results = query.all()
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2692, in all
    return self._iter().all()  # type: ignore
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2127, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.DiskFull) could not write to file "base/pgsql_tmp/pgsql_tmp2510281.0": No space left on device

[SQL: SELECT takers.buyer AS takers_buyer, takers."amountBought" AS "takers_amountBought", takers."amountSold" AS "takers_amountSold", takers."cumulativeMarkout" AS "takers_cumulativeMarkout", takers."meanMarkout" AS "takers_meanMarkout", takers.count AS takers_count, takers."windowSize" AS "takers_windowSize" 
FROM takers ORDER BY takers."cumulativeMarkout" DESC]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DiskFull: could not write to file "base/pgsql_tmp/pgsql_tmp2510281.0": No space left on device


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/curve-lp-metrics/curvemetrics/scripts/forever.py", line 324, in <module>
    models = main(models)
  File "/root/curve-lp-metrics/curvemetrics/scripts/forever.py", line 233, in main
    raise e
  File "/root/curve-lp-metrics/curvemetrics/scripts/forever.py", line 226, in main
    t = datahandler.get_takers()
  File "/root/curve-lp-metrics/curvemetrics/src/classes/datahandler.py", line 606, in get_takers
    results = query.all()
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2692, in all
    return self._iter().all()  # type: ignore
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2127, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/root/curve-lp-metrics/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.DiskFull) could not write to file "base/pgsql_tmp/pgsql_tmp2510281.0": No space left on device

[SQL: SELECT takers.buyer AS takers_buyer, takers."amountBought" AS "takers_amountBought", takers."amountSold" AS "takers_amountSold", takers."cumulativeMarkout" AS "takers_cumulativeMarkout", takers."meanMarkout" AS "takers_meanMarkout", takers.count AS takers_count, takers."windowSize" AS "takers_windowSize" 
FROM takers ORDER BY takers."cumulativeMarkout" DESC]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
